apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-court-fontend-app
  namespace: food-court
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-court-fontend-app
  template:
    metadata:
      labels:
        app: food-court-fontend-app
    spec:
      containers:
      - name: food-court-fontend-app
        image: mmregistry.mmvietnam.com:5000/food_court-fontend:12
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: mmregistry-secret
